import * as THREE from "three";
import {OrbitControls} from "three/addons/controls/OrbitControls.js";
import {CSS2DRenderer,CSS2DObject} from "three/addons/renderers/CSS2DRenderer.js";
import {floorData} from "./floor-data.js";
import {ybcReference} from "./ybc-reference.js";

const PLAN_WIDTH=18,PLAN_DEPTH=11.64,FLOOR_HEIGHT=1.15;
const BUILDING_X={SH:-10.5,WEH:10.5};
const floorById=new Map(floorData.floors.map(floor=>[floor.id,floor]));
const rooms=new Map();
for(const floor of floorData.floors)for(const room of floor.rooms){room.floorId=floor.id;room.building=floor.building;room.level=floor.level;rooms.set(room.id,room)}
const roomByName=new Map([...rooms.values()].map(room=>[room.name.toLowerCase(),room]));
const floorPathCache=new Map();

function findAnchor(floor){
  const prefixes=floor.building==="WEH"?[`${floor.level}001A`,`${floor.level}001`,`${floor.level}006`]:["909","901","900"];
  for(const suffix of prefixes){const match=floor.rooms.find(room=>room.id.endsWith(suffix));if(match)return {x:match.x,z:match.z}}
  const xs=floor.rooms.map(room=>room.x).sort((a,b)=>a-b),zs=floor.rooms.map(room=>room.z).sort((a,b)=>a-b);
  return {x:xs[Math.floor(xs.length/2)]??.5,z:zs[Math.floor(zs.length/2)]??.5};
}
for(const floor of floorData.floors)floor.anchor=findAnchor(floor);
const floorY=level=>level*FLOOR_HEIGHT;
function worldPoint(floor,x,z,lift=.18){return new THREE.Vector3(BUILDING_X[floor.building]+(x-floor.anchor.x)*PLAN_WIDTH,floorY(floor.level)+lift,(z-floor.anchor.z)*PLAN_DEPTH)}
function normalizedPoint(floor,world){return {x:(world.x-BUILDING_X[floor.building])/PLAN_WIDTH+floor.anchor.x,z:world.z/PLAN_DEPTH+floor.anchor.z}}

function inferredConnector(building,suffix,fallback){const points=[];for(const floor of floorData.floors.filter(item=>item.building===building)){const room=floor.rooms.find(item=>item.id.endsWith(suffix));if(room)points.push(worldPoint(floor,room.x,room.z,0))}if(!points.length)return fallback;return new THREE.Vector3(points.reduce((sum,p)=>sum+p.x,0)/points.length,0,points.reduce((sum,p)=>sum+p.z,0)/points.length)}
const connectorWorld={
  SH:{elevator:new THREE.Vector3(BUILDING_X.SH,0,0),stairs:[inferredConnector("SH","900",new THREE.Vector3(BUILDING_X.SH-2.5,0,-.2)),inferredConnector("SH","950",new THREE.Vector3(BUILDING_X.SH+2.4,0,.1))]},
  WEH:{elevator:new THREE.Vector3(BUILDING_X.WEH,0,0),stairs:[inferredConnector("WEH","129",new THREE.Vector3(BUILDING_X.WEH-3.1,0,-.3)),inferredConnector("WEH","432",new THREE.Vector3(BUILDING_X.WEH+2.8,0,.1))]}
};
function connectorPoint(building,mode,index=0){const connector=connectorWorld[building][mode];return Array.isArray(connector)?connector[index]:connector}
// Level 4 portals marked "TO WEAN HALL" and "TO SCOTT HALL" on the source plans.
const bridgePortal={SH:{x:.438,z:.403},WEH:{x:.153,z:.301}};

const container=document.querySelector("#scene"),status=document.querySelector("#scene-status");
const scene=new THREE.Scene();scene.background=new THREE.Color(0xdde9e5);scene.fog=new THREE.Fog(0xdde9e5,34,62);
const camera=new THREE.PerspectiveCamera(42,1,.1,120);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance",preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;container.appendChild(renderer.domElement);
const labelRenderer=new CSS2DRenderer();labelRenderer.domElement.style.cssText="position:absolute;inset:0;pointer-events:none";container.appendChild(labelRenderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=9;controls.maxDistance=60;controls.maxPolarAngle=Math.PI*.49;
scene.add(new THREE.HemisphereLight(0xffffff,0x667b76,2.3));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(-15,25,16);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(64,35),new THREE.MeshStandardMaterial({color:0xc6d7d1,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.3;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(64,40,0x91aaa4,0xb7c9c4);grid.position.y=-.28;scene.add(grid);

function htmlLabel(text,color="#172126"){const element=document.createElement("div");element.textContent=text;element.style.cssText=`background:${color}e8;color:white;padding:3px 6px;border-radius:3px;font:800 9px -apple-system,sans-serif;white-space:nowrap`;return new CSS2DObject(element)}
function roomLabel(room){const element=document.createElement("div");element.className="room-label";element.textContent=room.name.split(" ").at(-1);element.title=room.name;return new CSS2DObject(element)}
function floorBounds(floor,margin=.035){const xs=floor.rooms.map(room=>room.x),zs=floor.rooms.map(room=>room.z);return {left:Math.max(0,Math.min(...xs)-margin),right:Math.min(1,Math.max(...xs)+margin),top:Math.max(0,Math.min(...zs)-margin),bottom:Math.min(1,Math.max(...zs)+margin)}}
function mergeWallRuns(runs){const merged=[];for(const run of runs){let match;for(let index=merged.length-1;index>=0&&run.axis-merged[index].axis<=3;index--){const candidate=merged[index],overlap=Math.min(run.end,candidate.end)-Math.max(run.start,candidate.start),shorter=Math.min(run.end-run.start,candidate.end-candidate.start);if(overlap>shorter*.75){match=candidate;break}}if(match){match.start=Math.min(match.start,run.start);match.end=Math.max(match.end,run.end);match.axis=(match.axis*match.samples+run.axis)/(match.samples+1);match.samples++}else merged.push({...run,samples:1})}return merged}
function recognizeWalls(floor){
  const width=360,height=Math.round(width*floor.imageElement.height/floor.imageElement.width),canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;
  const context=canvas.getContext("2d",{willReadFrequently:true});context.drawImage(floor.imageElement,0,0,width,height);const rgba=context.getImageData(0,0,width,height).data,dark=new Uint8Array(width*height);
  for(let index=0;index<dark.length;index++){const pixel=index*4,red=rgba[pixel],green=rgba[pixel+1],blue=rgba[pixel+2],luminance=.2126*red+.7152*green+.0722*blue,chroma=Math.max(red,green,blue)-Math.min(red,green,blue);dark[index]=luminance<165&&chroma<35?1:0}
  const bounds=floorBounds(floor,.04),left=Math.floor(bounds.left*width),right=Math.ceil(bounds.right*width),top=Math.floor(bounds.top*height),bottom=Math.ceil(bounds.bottom*height);
  function scan(horizontal){const runs=[],axisStart=horizontal?top:left,axisEnd=horizontal?bottom:right,start=horizontal?left:top,end=horizontal?right:bottom,minLength=4;for(let axis=axisStart;axis<=axisEnd;axis++){let cursor=start;while(cursor<=end){const pixel=horizontal?axis*width+cursor:cursor*width+axis;if(!dark[pixel]){cursor++;continue}const runStart=cursor;while(cursor<=end&&dark[horizontal?axis*width+cursor:cursor*width+axis])cursor++;if(cursor-runStart>=minLength)runs.push({axis,start:runStart,end:cursor-1})}}return mergeWallRuns(runs)}
  floor.planRaster={width,height,dark};return {horizontal:scan(true).map(run=>({x1:run.start/(width-1),x2:run.end/(width-1),z:run.axis/(height-1)})),vertical:scan(false).map(run=>({x:run.axis/(width-1),z1:run.start/(height-1),z2:run.end/(height-1)}))}
}
function addRecognizedWalls(floor,group){const walls=recognizeWalls(floor),segments=[...walls.horizontal.map(wall=>({x:(wall.x1+wall.x2)/2,z:wall.z,xSize:(wall.x2-wall.x1)*PLAN_WIDTH,zSize:.055})),...walls.vertical.map(wall=>({x:wall.x,z:(wall.z1+wall.z2)/2,xSize:.055,zSize:(wall.z2-wall.z1)*PLAN_DEPTH}))];floor.wallSegments=segments;const geometry=new THREE.BoxGeometry(1,1,1),material=new THREE.MeshStandardMaterial({color:0x33494d,roughness:.82,transparent:true,opacity:.78}),mesh=new THREE.InstancedMesh(geometry,material,segments.length),matrix=new THREE.Matrix4(),quaternion=new THREE.Quaternion(),scale=new THREE.Vector3();segments.forEach((wall,index)=>{matrix.compose(worldPoint(floor,wall.x,wall.z,.34),quaternion,scale.set(wall.xSize,.52,wall.zSize));mesh.setMatrixAt(index,matrix)});mesh.instanceMatrix.needsUpdate=true;mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData={wallCount:segments.length,modelLayer:"architecture",modelType:"wall"};group.add(mesh);return segments.length}
function addSemanticSpaces(floor,group){
  const {width,height,dark}=floor.planRaster,closed=dilate(dark,width,height,3),bounds=floorBounds(floor,.04),left=Math.floor(bounds.left*width),right=Math.ceil(bounds.right*width),top=Math.floor(bounds.top*height),bottom=Math.ceil(bounds.bottom*height),regionAt=new Int32Array(width*height);regionAt.fill(-1);const regions=[];
  for(let y=top;y<=bottom;y++)for(let x=left;x<=right;x++){const start=y*width+x;if(closed[start]||regionAt[start]>=0)continue;const id=regions.length,queue=[start],pixels=[];let touchesBoundary=false;regionAt[start]=id;for(let head=0;head<queue.length;head++){const index=queue[head],px=index%width,py=Math.floor(index/width);pixels.push(index);if(px===left||px===right||py===top||py===bottom)touchesBoundary=true;for(const next of [index-1,index+1,index-width,index+width]){const nx=next%width,ny=Math.floor(next/width);if(nx<left||nx>right||ny<top||ny>bottom||closed[next]||regionAt[next]>=0)continue;regionAt[next]=id;queue.push(next)}}regions.push({pixels,touchesBoundary,roomCount:0,type:"other"})}
  function nearestRegion(room){const ox=Math.round(room.x*(width-1)),oy=Math.round(room.z*(height-1));for(let radius=0;radius<16;radius++)for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){if(Math.abs(dx)!==radius&&Math.abs(dy)!==radius)continue;const x=ox+dx,y=oy+dy;if(x<left||x>right||y<top||y>bottom)continue;const id=regionAt[y*width+x];if(id>=0&&!regions[id].touchesBoundary)return id}return -1}
  for(const room of floor.rooms){const id=nearestRegion(room);if(id>=0)regions[id].roomCount++}
  const counts={room:0,corridor:0,other:0,total:0},colors={room:[27,142,139,112],corridor:[226,177,61,118],other:[116,129,132,88]},overlay=document.createElement("canvas");overlay.width=width;overlay.height=height;const overlayContext=overlay.getContext("2d"),image=overlayContext.createImageData(width,height);
  for(const region of regions){if(region.touchesBoundary||region.pixels.length<6)continue;region.type=region.roomCount?"room":region.pixels.length>180?"corridor":"other";counts[region.type]++;counts.total++;const color=colors[region.type];for(const index of region.pixels){const pixel=index*4;image.data[pixel]=color[0];image.data[pixel+1]=color[1];image.data[pixel+2]=color[2];image.data[pixel+3]=color[3]}}
  overlayContext.putImageData(image,0,0);const texture=new THREE.CanvasTexture(overlay);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;const center=worldPoint(floor,.5,.5,.09),surface=new THREE.Mesh(new THREE.PlaneGeometry(PLAN_WIDTH,PLAN_DEPTH),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,side:THREE.DoubleSide}));surface.rotation.x=-Math.PI/2;surface.position.copy(center);surface.renderOrder=1;surface.userData.spaceCounts=counts;group.add(surface);floor.spaceCounts=counts;delete floor.planRaster;return counts
}
function addYbcReference(floor,group){
  const graph=ybcReference.floors[floor.id];if(!graph)return;
  const normalized=point=>({x:point[0]/graph.pageWidth,z:point[1]/graph.pageHeight}),position=(point,lift=.64)=>{const value=normalized(point);return worldPoint(floor,value.x,value.z,lift)},nodeById=new Map(graph.nodes.map(node=>[node.id,node]));
  const roomMetadata=new Map(graph.nodes.filter(node=>node.type==="room"&&node.label).map(node=>[node.label.toUpperCase(),node]));for(const room of floor.rooms){const metadata=roomMetadata.get(room.id.split("-").at(-1));if(metadata){room.roomType=metadata.room_type;room.department=metadata.department}}
  function lineSegments(lines,color,opacity=1){const points=[];for(const line of lines)for(let index=1;index<line.points.length;index++)points.push(position(line.points[index-1]),position(line.points[index]));const geometry=new THREE.BufferGeometry().setFromPoints(points),material=new THREE.LineBasicMaterial({color,transparent:opacity<1,opacity,depthTest:false}),mesh=new THREE.LineSegments(geometry,material);mesh.renderOrder=4;group.add(mesh);return lines.length}
  lineSegments(graph.passageways,0xd97706);
  lineSegments(graph.doorAttachments,0x94a3b8,.9);
  const doorEdges=graph.edges.map(edge=>{const from=nodeById.get(edge.from_node),to=nodeById.get(edge.to_node);return {points:edge.points?.length>=2?edge.points:from&&to?[[from.x,from.y],[to.x,to.y]]:[]}}).filter(edge=>edge.points.length>=2);lineSegments(doorEdges,0x10b981,.85);
  function nodeInstances(type,color,geometry,lift=.7){const nodes=graph.nodes.filter(node=>node.type===type),material=new THREE.MeshStandardMaterial({color,roughness:.5}),mesh=new THREE.InstancedMesh(geometry,material,nodes.length),matrix=new THREE.Matrix4();nodes.forEach((node,index)=>{matrix.setPosition(position([node.x,node.y],lift));mesh.setMatrixAt(index,matrix)});mesh.instanceMatrix.needsUpdate=true;mesh.castShadow=true;mesh.renderOrder=5;mesh.userData={modelLayer:"facilities",modelType:type};group.add(mesh);return nodes.length}
  function doorInstances(){const nodes=graph.nodes.filter(node=>node.type==="door"),attachments=new Map(graph.doorAttachments.map(attachment=>[attachment.door_node_id,attachment.points])),geometry=new THREE.BoxGeometry(1,1,1),material=new THREE.MeshStandardMaterial({color:0x10b981,roughness:.5}),mesh=new THREE.InstancedMesh(geometry,material,nodes.length),matrix=new THREE.Matrix4(),quaternion=new THREE.Quaternion(),scale=new THREE.Vector3(.28,.52,.07),up=new THREE.Vector3(0,1,0);nodes.forEach((node,index)=>{const points=attachments.get(node.id),doorPosition=position([node.x,node.y],.34);let angle;if(points?.length>1){const start=points[0],end=points.at(-1),normalX=(end[0]-start[0])*PLAN_WIDTH/graph.pageWidth,normalZ=(end[1]-start[1])*PLAN_DEPTH/graph.pageHeight;angle=Math.atan2(-normalX,-normalZ)}else{const nearest=floor.wallSegments.reduce((best,wall)=>{const center=worldPoint(floor,wall.x,wall.z,0),horizontal=wall.xSize>wall.zSize,closestX=horizontal?Math.max(center.x-wall.xSize/2,Math.min(center.x+wall.xSize/2,doorPosition.x)):center.x,closestZ=horizontal?center.z:Math.max(center.z-wall.zSize/2,Math.min(center.z+wall.zSize/2,doorPosition.z)),distance=Math.hypot(doorPosition.x-closestX,doorPosition.z-closestZ);return !best||distance<best.distance?{distance,horizontal}:best},null);angle=nearest?.horizontal?0:-Math.PI/2}quaternion.setFromAxisAngle(up,angle);matrix.compose(doorPosition,quaternion,scale);mesh.setMatrixAt(index,matrix)});mesh.instanceMatrix.needsUpdate=true;mesh.castShadow=true;mesh.receiveShadow=true;mesh.renderOrder=5;mesh.userData={modelLayer:"architecture",modelType:"door",orientedCount:nodes.length};group.add(mesh);return nodes.length}
  const doorCount=doorInstances(),stairCount=nodeInstances("stair",0x7652a8,new THREE.BoxGeometry(.24,.22,.24)),elevatorCount=nodeInstances("elevator",0x087f82,new THREE.CylinderGeometry(.14,.14,.25,10));
  const label=htmlLabel("YBC VERIFIED PASSAGES","#8b5e12");label.position.copy(worldPoint(floor,.5,.12,.9));group.add(label);floor.referenceCounts={passages:graph.passageways.length,doors:doorCount,stairs:stairCount,elevators:elevatorCount}
}
const textureLoader=new THREE.TextureLoader(),floorObjects=[];
async function addFloor(floor){
  const texture=await textureLoader.loadAsync(floor.image);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();floor.imageElement=texture.image;
  const group=new THREE.Group();group.userData.floor=floor;
  const center=worldPoint(floor,.5,.5,0);const base=new THREE.Mesh(new THREE.BoxGeometry(PLAN_WIDTH,.12,PLAN_DEPTH),new THREE.MeshStandardMaterial({color:floor.building==="SH"?0x7baea3:0xd5b765,roughness:.8}));base.position.set(center.x,floorY(floor.level),center.z);base.receiveShadow=true;group.add(base);
  const plan=new THREE.Mesh(new THREE.PlaneGeometry(PLAN_WIDTH,PLAN_DEPTH),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide,transparent:true,opacity:.72}));plan.rotation.x=-Math.PI/2;plan.position.set(center.x,floorY(floor.level)+.07,center.z);group.add(plan);
  floor.wallCount=addRecognizedWalls(floor,group);
  addSemanticSpaces(floor,group);
  addYbcReference(floor,group);
  const roomLabels=new THREE.Group();roomLabels.visible=false;for(const room of floor.rooms){const label=roomLabel(room);label.position.copy(worldPoint(floor,room.x,room.z,.3));roomLabels.add(label)}group.add(roomLabels);
  const label=htmlLabel(`${floor.buildingName} · ${floor.levelLabel}`);label.position.copy(worldPoint(floor,.5,.08,.45));group.add(label);scene.add(group);floorObjects.push({floor,group,roomLabels});
}
status.textContent=`Loading ${floorData.roomCount.toLocaleString()} rooms…`;
await Promise.all(floorData.floors.map(addFloor));

const facilities=new THREE.Group();scene.add(facilities);const elevatorCabins=[];
function addFacilities(building){
  const buildingFloors=floorData.floors.filter(floor=>floor.building===building).sort((a,b)=>a.level-b.level),min=floorY(buildingFloors[0].level),max=floorY(buildingFloors.at(-1).level);
  const elevator=connectorWorld[building].elevator,shaft=new THREE.Mesh(new THREE.BoxGeometry(.72,max-min+.8,.72),new THREE.MeshStandardMaterial({color:0x5b8d98,transparent:true,opacity:.25,metalness:.3}));shaft.position.set(elevator.x,(min+max)/2,elevator.z);facilities.add(shaft);const cabin=new THREE.Mesh(new THREE.BoxGeometry(.56,.5,.56),new THREE.MeshStandardMaterial({color:0x087f82,metalness:.5}));cabin.position.set(elevator.x,min+.3,elevator.z);cabin.userData={min,max};facilities.add(cabin);elevatorCabins.push(cabin);
  for(const [stairIndex,stair] of connectorWorld[building].stairs.entries()){for(let index=0;index<buildingFloors.length-1;index++){const low=buildingFloors[index],high=buildingFloors[index+1];for(let step=0;step<9;step++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.6,.09,.18),new THREE.MeshStandardMaterial({color:0x526970}));mesh.position.set(stair.x,floorY(low.level)+.12+(floorY(high.level)-floorY(low.level))*step/9,stair.z-.45+step*.1);facilities.add(mesh)}}const label=htmlLabel(`STAIRS ${stairIndex+1}`,"#455b61");label.position.set(stair.x,floorY(4)+.65,stair.z);facilities.add(label)}
  const elevatorLabel=htmlLabel("ELEVATOR","#087f82");elevatorLabel.position.set(elevator.x,floorY(4)+.65,elevator.z);facilities.add(elevatorLabel)
}
addFacilities("SH");addFacilities("WEH");
const sh4=floorById.get("SH-4"),weh4=floorById.get("WEH-4"),bridgeStart=worldPoint(sh4,bridgePortal.SH.x,bridgePortal.SH.z,.14),bridgeEnd=worldPoint(weh4,bridgePortal.WEH.x,bridgePortal.WEH.z,.14);const bridgeLength=bridgeStart.distanceTo(bridgeEnd),bridge=new THREE.Mesh(new THREE.BoxGeometry(bridgeLength,.16,.72),new THREE.MeshStandardMaterial({color:0xdde4e2,metalness:.2}));bridge.position.copy(bridgeStart).lerp(bridgeEnd,.5);bridge.position.y=floorY(4)+.1;bridge.rotation.y=-Math.atan2(bridgeEnd.z-bridgeStart.z,bridgeEnd.x-bridgeStart.x);scene.add(bridge);

class Heap{constructor(){this.a=[]}push(value,priority){const a=this.a,node=[priority,value];a.push(node);let i=a.length-1;while(i){const p=(i-1)>>1;if(a[p][0]<=priority)break;a[i]=a[p];i=p}a[i]=node}pop(){const a=this.a,root=a[0],last=a.pop();if(a.length){let i=0;while(true){let c=i*2+1;if(c>=a.length)break;if(c+1<a.length&&a[c+1][0]<a[c][0])c++;if(a[c][0]>=last[0])break;a[i]=a[c];i=c}a[i]=last}return root?.[1]}get length(){return this.a.length}}
function dilate(source,width,height,radius){const horizontal=new Uint8Array(source.length),out=new Uint8Array(source.length);for(let y=0;y<height;y++){let count=0;for(let x=0;x<width;x++){if(x+radius<width)count+=source[y*width+x+radius];if(x-radius-1>=0)count-=source[y*width+x-radius-1];horizontal[y*width+x]=count>0?1:0}}for(let x=0;x<width;x++){let count=0;for(let y=0;y<height;y++){if(y+radius<height)count+=horizontal[(y+radius)*width+x];if(y-radius-1>=0)count-=horizontal[(y-radius-1)*width+x];out[y*width+x]=count>0?1:0}}return out}
function prepareGrid(floor){
  if(floor.grid)return floor.grid;
  const width=420,height=Math.round(width*floor.imageElement.height/floor.imageElement.width),canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;
  const context=canvas.getContext("2d",{willReadFrequently:true});context.drawImage(floor.imageElement,0,0,width,height);
  const rgba=context.getImageData(0,0,width,height).data,dark=new Uint8Array(width*height);
  for(let i=0;i<dark.length;i++){const p=i*4,l=.2126*rgba[p]+.7152*rgba[p+1]+.0722*rgba[p+2];dark[i]=l<165?1:0}
  const closed=dilate(dark,width,height,5),outside=new Uint8Array(dark.length),queue=[];
  for(let x=0;x<width;x++)queue.push(x,(height-1)*width+x);for(let y=0;y<height;y++)queue.push(y*width,y*width+width-1);
  for(let head=0;head<queue.length;head++){const i=queue[head];if(outside[i]||closed[i])continue;outside[i]=1;const x=i%width,y=Math.floor(i/width);if(x)queue.push(i-1);if(x+1<width)queue.push(i+1);if(y)queue.push(i-width);if(y+1<height)queue.push(i+width)}
  const bounds=floorBounds(floor),allowed=new Uint8Array(dark.length);
  for(let i=0;i<allowed.length;i++){const x=(i%width)/(width-1),z=Math.floor(i/width)/(height-1),within=x>=bounds.left&&x<=bounds.right&&z>=bounds.top&&z<=bounds.bottom;allowed[i]=!dark[i]&&within&&(!outside[i]||closed[i])?1:0}
  floor.grid={width,height,allowed,dark,closed,outside};return floor.grid;
}
function nearestAllowed(grid,point){const ox=Math.round(point.x*(grid.width-1)),oy=Math.round(point.z*(grid.height-1));for(let radius=0;radius<28;radius++)for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){if(Math.abs(dx)!==radius&&Math.abs(dy)!==radius)continue;const x=ox+dx,y=oy+dy;if(x>=0&&y>=0&&x<grid.width&&y<grid.height&&grid.allowed[y*grid.width+x])return {x,y}}return null}
function rasterPath(floor,start,end){const cacheKey=`${floor.id}:${start.x.toFixed(4)},${start.z.toFixed(4)}:${end.x.toFixed(4)},${end.z.toFixed(4)}`;if(floorPathCache.has(cacheKey))return floorPathCache.get(cacheKey);const grid=prepareGrid(floor),a=nearestAllowed(grid,start),b=nearestAllowed(grid,end);if(!a)throw new Error(`No mapped walkspace near start point ${start.x.toFixed(3)}, ${start.z.toFixed(3)} on ${floor.buildingName} ${floor.levelLabel}`);if(!b)throw new Error(`No mapped walkspace near destination point ${end.x.toFixed(3)}, ${end.z.toFixed(3)} on ${floor.buildingName} ${floor.levelLabel}`);const size=grid.width*grid.height,g=new Float32Array(size);g.fill(Infinity);const previous=new Int32Array(size);previous.fill(-1);const startIndex=a.y*grid.width+a.x,target=b.y*grid.width+b.x,heap=new Heap();g[startIndex]=0;heap.push(startIndex,0);const moves=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];while(heap.length){const current=heap.pop();if(current===target)break;const x=current%grid.width,y=Math.floor(current/grid.width);for(const [dx,dy] of moves){const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=grid.width||yy>=grid.height)continue;const next=yy*grid.width+xx;if(!grid.allowed[next])continue;if(dx&&dy&&(!grid.allowed[y*grid.width+xx]||!grid.allowed[yy*grid.width+x]))continue;const candidate=g[current]+(dx&&dy?Math.SQRT2:1);if(candidate<g[next]){g[next]=candidate;previous[next]=current;heap.push(next,candidate+Math.hypot(xx-b.x,yy-b.y))}}}if(previous[target]<0&&target!==startIndex)throw new Error(`No human-reachable walkspace route on ${floor.buildingName} ${floor.levelLabel}`);const pixels=[];for(let current=target;current!==-1;current=previous[current]){pixels.push(current);if(current===startIndex)break}pixels.reverse();const simplified=[pixels[0]];let priorDirection;for(let index=1;index<pixels.length;index++){const dx=pixels[index]%grid.width-pixels[index-1]%grid.width,dy=Math.floor(pixels[index]/grid.width)-Math.floor(pixels[index-1]/grid.width),direction=`${dx},${dy}`;if(priorDirection&&direction!==priorDirection)simplified.push(pixels[index-1]);priorDirection=direction}simplified.push(pixels.at(-1));const path=simplified.map(index=>({x:(index%grid.width)/(grid.width-1),z:Math.floor(index/grid.width)/(grid.height-1)}));floorPathCache.set(cacheKey,path);floorPathCache.set(`${floor.id}:${end.x.toFixed(4)},${end.z.toFixed(4)}:${start.x.toFixed(4)},${start.z.toFixed(4)}`,[...path].reverse());return path}

function appendFloorPath(route,floor,start,end){const normalized=rasterPath(floor,start,end);for(const point of normalized)route.points.push(worldPoint(floor,point.x,point.z,.2));route.steps.push(`Follow mapped walkspace on ${floor.buildingName} ${floor.levelLabel}.`)}
function appendVertical(route,building,fromFloor,toFloor,mode,connectorIndex=0){const connector=connectorPoint(building,mode,connectorIndex),levels=floorData.floors.filter(f=>f.building===building&&f.level>=Math.min(fromFloor.level,toFloor.level)&&f.level<=Math.max(fromFloor.level,toFloor.level)).sort((a,b)=>fromFloor.level<toFloor.level?a.level-b.level:b.level-a.level);for(const floor of levels){const p=connector.clone();p.y=floorY(floor.level)+.2;if(mode==="stairs"){p.x+=levels.indexOf(floor)%2?.18:-.18;p.z+=levels.indexOf(floor)%2?.16:-.16}route.points.push(p)}route.types.push(mode);const instruction={elevator:"Take the elevator",stairs:"Use the stairs"}[mode];route.steps.push(`${instruction}${mode==="stairs"?` ${connectorIndex+1}`:""} to ${toFloor.buildingName} ${toFloor.levelLabel}.`)}
function connectorNorm(floor,mode,connectorIndex=0){return normalizedPoint(floor,connectorPoint(floor.building,mode,connectorIndex))}
function roomNorm(room){return {x:room.x,z:room.z}}
function buildRoute(startRoom,endRoom,mode,connectorIndices={}){const route={points:[],steps:[`Exit ${startRoom.name} through its mapped doorway.`],types:[],mode},startFloor=floorById.get(startRoom.floorId),endFloor=floorById.get(endRoom.floorId),connectorIndex=building=>connectorIndices[building]||0;
  if(startFloor.id===endFloor.id)appendFloorPath(route,startFloor,roomNorm(startRoom),roomNorm(endRoom));
  else if(startFloor.building===endFloor.building){const index=connectorIndex(startFloor.building);appendFloorPath(route,startFloor,roomNorm(startRoom),connectorNorm(startFloor,mode,index));appendVertical(route,startFloor.building,startFloor,endFloor,mode,index);appendFloorPath(route,endFloor,connectorNorm(endFloor,mode,index),roomNorm(endRoom));}
  else{const startBridge=floorById.get(`${startFloor.building}-4`),endBridge=floorById.get(`${endFloor.building}-4`),startIndex=connectorIndex(startFloor.building),endIndex=connectorIndex(endFloor.building);let startAt=roomNorm(startRoom);if(startFloor.level!==4){appendFloorPath(route,startFloor,startAt,connectorNorm(startFloor,mode,startIndex));appendVertical(route,startFloor.building,startFloor,startBridge,mode,startIndex);startAt=connectorNorm(startBridge,mode,startIndex)}appendFloorPath(route,startBridge,startAt,bridgePortal[startFloor.building]);route.points.push(startFloor.building==="SH"?bridgeStart:bridgeEnd,startFloor.building==="SH"?bridgeEnd:bridgeStart);route.types.push("bridge");route.steps.push("Cross between buildings through the Level 4 bridge.");let endAt=bridgePortal[endFloor.building];if(endFloor.level!==4){appendFloorPath(route,endBridge,endAt,connectorNorm(endBridge,mode,endIndex));appendVertical(route,endFloor.building,endBridge,endFloor,mode,endIndex);endAt=connectorNorm(endFloor,mode,endIndex)}appendFloorPath(route,endFloor,endAt,roomNorm(endRoom));}
  route.steps.push(`Enter ${endRoom.name}.`);return route}
function routeLength(route){let length=0;for(let index=1;index<route.points.length;index++)length+=route.points[index-1].distanceTo(route.points[index]);return length}
function routeCost(route){const connectorPenalty={stairs:0,elevator:5};return routeLength(route)+(connectorPenalty[route.mode]||0)}
async function planRoute(startRoom,endRoom,accessible){
  const startFloor=floorById.get(startRoom.floorId),endFloor=floorById.get(endRoom.floorId);
  if(startFloor.id===endFloor.id){const route=buildRoute(startRoom,endRoom,"walk");route.length=routeLength(route);return route}
  const candidates=[],errors=[],buildings=[...new Set([startFloor.building,endFloor.building])],choices=accessible?[{mode:"elevator",indices:{}}]:[{mode:"elevator",indices:{}}];
  if(!accessible){let selections=[{}];for(const building of buildings)selections=selections.flatMap(selection=>connectorWorld[building].stairs.map((_,index)=>({...selection,[building]:index})));choices.unshift(...selections.map(indices=>({mode:"stairs",indices})))}
  for(const choice of choices){try{const route=buildRoute(startRoom,endRoom,choice.mode,choice.indices);route.length=routeLength(route);route.cost=routeCost(route);candidates.push(route)}catch(error){errors.push(`${choice.mode}: ${error.message}`)}}
  if(!candidates.length)throw new Error(errors[0]||"No connector is reachable from the selected rooms");
  return candidates.sort((a,b)=>a.cost-b.cost)[0]
}

let routeGroup,routeLine,autoRotate=false;
function pin(position,color){const group=new THREE.Group(),cone=new THREE.Mesh(new THREE.ConeGeometry(.18,.5,16),new THREE.MeshStandardMaterial({color})),ring=new THREE.Mesh(new THREE.TorusGeometry(.22,.045,8,20),new THREE.MeshBasicMaterial({color}));cone.rotation.x=Math.PI;cone.position.y=.29;ring.rotation.x=Math.PI/2;group.add(cone,ring);group.position.copy(position);return group}
function drawRoute(route,start,end){
  if(routeGroup){routeGroup.traverse(object=>{if(object.isCSS2DObject)object.element.remove();object.geometry?.dispose();if(object.material)Object.values(Array.isArray(object.material)?object.material:[object.material]).forEach(material=>material.dispose())});scene.remove(routeGroup)}
  routeGroup=new THREE.Group();routeLine=new THREE.Group();
  const points=route.points.map(point=>point.clone().add(new THREE.Vector3(0,.48,0))),material=new THREE.MeshBasicMaterial({color:0xff3125,depthTest:false,depthWrite:false}),up=new THREE.Vector3(0,1,0);
  for(let index=0;index<points.length-1;index++){
    const beginning=points[index],ending=points[index+1],direction=ending.clone().sub(beginning),length=direction.length();
    if(length<.001)continue;
    const segment=new THREE.Mesh(new THREE.CylinderGeometry(.1,.1,length,12),material);
    segment.position.copy(beginning).lerp(ending,.5);segment.quaternion.setFromUnitVectors(up,direction.normalize());segment.renderOrder=10;routeLine.add(segment);
  }
  for(const point of points){const joint=new THREE.Mesh(new THREE.SphereGeometry(.12,12,8),material);joint.position.copy(point);joint.renderOrder=10;routeLine.add(joint)}
  routeGroup.add(routeLine,pin(points[0],0xff3125),pin(points.at(-1),0x087f82));
  const startLabel=htmlLabel(start.name,"#ff3125");startLabel.position.copy(points[0]).add(new THREE.Vector3(0,.7,0));const endLabel=htmlLabel(end.name,"#087f82");endLabel.position.copy(points.at(-1)).add(new THREE.Vector3(0,.7,0));routeGroup.add(startLabel,endLabel);scene.add(routeGroup);
  const middle=points[Math.floor(points.length/2)];controls.target.copy(middle);camera.position.set(middle.x+11,middle.y+10,middle.z+13);controls.update()
}

const from=document.querySelector("#from"),to=document.querySelector("#to"),result=document.querySelector("#result"),directionContent=document.querySelector("#direction-content"),sheetHandle=document.querySelector("#sheet-handle"),accessible=document.querySelector("#accessible"),options=document.querySelector("#room-options"),floorFilter=document.querySelector("#floor-filter"),roomNumbers=document.querySelector("#room-numbers");
for(const floor of [...floorData.floors].sort((a,b)=>a.building.localeCompare(b.building)||a.level-b.level)){const option=document.createElement("option");option.value=floor.id;option.textContent=`${floor.buildingName} ${floor.levelLabel}`;floorFilter.append(option);for(const room of floor.rooms){const item=document.createElement("option");item.value=room.name;item.label=`${floor.buildingName} · ${floor.levelLabel}`;options.append(item)}}
from.value="Scott 4N103";to.value="Wean 4325";
function selectedRoom(input){return roomByName.get(input.value.trim().toLowerCase())}
function setSheet(expanded){result.classList.toggle("expanded",expanded);result.style.removeProperty("transform");sheetHandle.setAttribute("aria-expanded",String(expanded));sheetHandle.setAttribute("aria-label",`${expanded?"Collapse":"Expand"} route directions`)}
function showDirections(html){directionContent.innerHTML=html;result.classList.add("show");result.setAttribute("aria-hidden","false");setSheet(true);directionContent.scrollTop=0}
async function show(){const start=selectedRoom(from),end=selectedRoom(to);if(!start||!end){showDirections("<div class='route-head'><h2>Select a room from the list</h2></div>");return}if(start.id===end.id){showDirections("<div class='route-head'><h2>You are already there</h2></div>");return}document.querySelector("#go").disabled=true;status.textContent="Checking mapped walkspace…";try{const route=await planRoute(start,end,accessible.checked),mode=route.types.includes("elevator")?"Elevator":route.types.includes("stairs")?"Stairs":route.types.includes("bridge")?"Level 4 bridge":"Direct walkspace";drawRoute(route,start,end);showDirections(`<div class="route-head"><h2>${start.name} → ${end.name}</h2><span>${route.steps.length} steps</span></div><div class="route-meta"><span class="recommended">RECOMMENDED</span><span>${mode}</span><span>Map walkspace</span>${route.types.includes("bridge")?"<span>Bridge required</span>":""}</div><ol>${route.steps.map((step,index)=>`<li><b>${index+1}</b><span>${step}</span></li>`).join("")}</ol>`);status.textContent=`Reachable route · ${start.name} → ${end.name}`}catch(error){showDirections(`<div class="route-head"><h2>No verified route</h2></div><p>${error.message}. The app will not draw a path through walls or air.</p>`);status.textContent="No verified walkspace route"}finally{document.querySelector("#go").disabled=false}}
let sheetDragStart=0,sheetStartOffset=0,sheetMoved=false;
function sheetLimit(){return Math.max(0,result.offsetHeight-sheetHandle.offsetHeight)}
sheetHandle.addEventListener("pointerdown",event=>{sheetDragStart=event.clientY;sheetStartOffset=result.classList.contains("expanded")?0:sheetLimit();sheetMoved=false;sheetHandle.setPointerCapture(event.pointerId);result.classList.add("dragging")});
sheetHandle.addEventListener("pointermove",event=>{if(!sheetHandle.hasPointerCapture(event.pointerId))return;const offset=Math.max(0,Math.min(sheetLimit(),sheetStartOffset+event.clientY-sheetDragStart));sheetMoved=sheetMoved||Math.abs(event.clientY-sheetDragStart)>4;result.style.transform=`translateY(${offset}px)`});
sheetHandle.addEventListener("pointerup",event=>{if(!sheetHandle.hasPointerCapture(event.pointerId))return;const distance=event.clientY-sheetDragStart,offset=Math.max(0,Math.min(sheetLimit(),sheetStartOffset+distance));sheetMoved=sheetMoved||Math.abs(distance)>4;sheetHandle.releasePointerCapture(event.pointerId);result.classList.remove("dragging");setSheet(offset<sheetLimit()/2)});
sheetHandle.addEventListener("click",()=>{if(sheetMoved){sheetMoved=false;return}setSheet(!result.classList.contains("expanded"))});
function applyVisibility(){const building=document.querySelector("[data-building].active").dataset.building,floorId=floorFilter.value;for(const item of floorObjects){item.group.visible=(building==="all"||item.floor.building===building)&&(floorId==="all"||item.floor.id===floorId);item.roomLabels.visible=roomNumbers.checked&&item.group.visible&&floorId===item.floor.id}if(floorId!=="all"){const floor=floorById.get(floorId),center=worldPoint(floor,.5,.5,.1);controls.target.copy(center);camera.position.set(center.x+1,center.y+15,center.z+13);controls.update()}}
document.querySelectorAll("[data-building]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-building]").forEach(item=>item.classList.remove("active"));button.classList.add("active");floorFilter.value="all";applyVisibility()});floorFilter.onchange=applyVisibility;roomNumbers.onchange=applyVisibility;
document.querySelector("#go").onclick=show;document.querySelector("#swap").onclick=()=>{const value=from.value;from.value=to.value;to.value=value;show()};document.querySelector("#reset-view").onclick=()=>{camera.position.set(28,20,28);controls.target.set(0,floorY(4),0);controls.update()};document.querySelector("#rotate").onclick=event=>{autoRotate=!autoRotate;event.currentTarget.classList.toggle("active",autoRotate)};document.querySelectorAll(".examples button").forEach(button=>button.onclick=()=>{from.value=rooms.get(button.dataset.from)?.name||"";to.value=rooms.get(button.dataset.to)?.name||"";show()});
function resize(){const width=container.clientWidth,height=container.clientHeight;camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false);labelRenderer.setSize(width,height)}function animate(time=0){requestAnimationFrame(animate);if(autoRotate)scene.rotation.y+=.002;for(const cabin of elevatorCabins)cabin.position.y=cabin.userData.min+.3+(Math.sin(time*.0007)+1)*(cabin.userData.max-cabin.userData.min)/2;controls.update();renderer.render(scene,camera);labelRenderer.render(scene,camera)}
camera.position.set(28,20,28);controls.target.set(0,floorY(4),0);resize();animate();addEventListener("resize",resize);const recognizedWallCount=floorData.floors.reduce((sum,floor)=>sum+floor.wallCount,0),classifiedSpaceCount=floorData.floors.reduce((sum,floor)=>sum+floor.spaceCounts.total,0),referencePassageCount=floorData.floors.reduce((sum,floor)=>sum+(floor.referenceCounts?.passages||0),0);status.textContent=`${floorData.roomCount.toLocaleString()} rooms · ${recognizedWallCount.toLocaleString()} walls · ${classifiedSpaceCount.toLocaleString()} spaces · ${referencePassageCount.toLocaleString()} YBC passages`;
