import * as THREE from "three";
import {OrbitControls} from "three/addons/controls/OrbitControls.js";
import {CSS2DRenderer,CSS2DObject} from "three/addons/renderers/CSS2DRenderer.js";
import {floorData} from "./floor-data.js";

const PLAN_WIDTH=18,PLAN_DEPTH=11.64,FLOOR_HEIGHT=1.15;
const BUILDING_X={SH:-10.5,WEH:10.5};
const floorById=new Map(floorData.floors.map(floor=>[floor.id,floor]));
const rooms=new Map();
for(const floor of floorData.floors)for(const room of floor.rooms){room.floorId=floor.id;room.building=floor.building;room.level=floor.level;rooms.set(room.id,room)}
const roomByName=new Map([...rooms.values()].map(room=>[room.name.toLowerCase(),room]));
const floorPathCache=new Map();

function findAnchor(floor){
  const prefixes=floor.building==="WEH"?[`${floor.level}001A`,`${floor.level}001`,`${floor.level}006`]:["909","901","900"];
  for(const suffix of prefixes){const match=floor.rooms.find(room=>room.id.endsWith(suffix));if(match)return {x:match.x,z:match.z}}
  const xs=floor.rooms.map(room=>room.x).sort((a,b)=>a-b),zs=floor.rooms.map(room=>room.z).sort((a,b)=>a-b);
  return {x:xs[Math.floor(xs.length/2)]??.5,z:zs[Math.floor(zs.length/2)]??.5};
}
for(const floor of floorData.floors)floor.anchor=findAnchor(floor);
const floorY=level=>level*FLOOR_HEIGHT;
function worldPoint(floor,x,z,lift=.18){return new THREE.Vector3(BUILDING_X[floor.building]+(x-floor.anchor.x)*PLAN_WIDTH,floorY(floor.level)+lift,(z-floor.anchor.z)*PLAN_DEPTH)}
function normalizedPoint(floor,world){return {x:(world.x-BUILDING_X[floor.building])/PLAN_WIDTH+floor.anchor.x,z:world.z/PLAN_DEPTH+floor.anchor.z}}

function inferredConnector(building,suffix,fallback){const points=[];for(const floor of floorData.floors.filter(item=>item.building===building)){const room=floor.rooms.find(item=>item.id.endsWith(suffix));if(room)points.push(worldPoint(floor,room.x,room.z,0))}if(!points.length)return fallback;return new THREE.Vector3(points.reduce((sum,p)=>sum+p.x,0)/points.length,0,points.reduce((sum,p)=>sum+p.z,0)/points.length)}
const connectorWorld={
  SH:{elevator:new THREE.Vector3(BUILDING_X.SH,0,0),stairs:inferredConnector("SH","900",new THREE.Vector3(BUILDING_X.SH-2.5,0,-.2)),escalator:inferredConnector("SH","950",new THREE.Vector3(BUILDING_X.SH+2.4,0,.1))},
  WEH:{elevator:new THREE.Vector3(BUILDING_X.WEH,0,0),stairs:inferredConnector("WEH","129",new THREE.Vector3(BUILDING_X.WEH-3.1,0,-.3)),escalator:inferredConnector("WEH","432",new THREE.Vector3(BUILDING_X.WEH+2.8,0,.1))}
};
const bridgePortal={SH:{x:.49,z:.30},WEH:{x:.49,z:.31}};

const container=document.querySelector("#scene"),status=document.querySelector("#scene-status");
const scene=new THREE.Scene();scene.background=new THREE.Color(0xdde9e5);scene.fog=new THREE.Fog(0xdde9e5,34,62);
const camera=new THREE.PerspectiveCamera(42,1,.1,120);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance",preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;container.appendChild(renderer.domElement);
const labelRenderer=new CSS2DRenderer();labelRenderer.domElement.style.cssText="position:absolute;inset:0;pointer-events:none";container.appendChild(labelRenderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=9;controls.maxDistance=60;controls.maxPolarAngle=Math.PI*.49;
scene.add(new THREE.HemisphereLight(0xffffff,0x667b76,2.3));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(-15,25,16);sun.castShadow=true;scene.add(sun);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(64,35),new THREE.MeshStandardMaterial({color:0xc6d7d1,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.3;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(64,40,0x91aaa4,0xb7c9c4);grid.position.y=-.28;scene.add(grid);

function htmlLabel(text,color="#172126"){const element=document.createElement("div");element.textContent=text;element.style.cssText=`background:${color}e8;color:white;padding:3px 6px;border-radius:3px;font:800 9px -apple-system,sans-serif;white-space:nowrap`;return new CSS2DObject(element)}
const textureLoader=new THREE.TextureLoader(),floorObjects=[];
async function addFloor(floor){
  const texture=await textureLoader.loadAsync(floor.image);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();floor.imageElement=texture.image;
  const group=new THREE.Group();group.userData.floor=floor;
  const center=worldPoint(floor,.5,.5,0);const base=new THREE.Mesh(new THREE.BoxGeometry(PLAN_WIDTH,.12,PLAN_DEPTH),new THREE.MeshStandardMaterial({color:floor.building==="SH"?0x7baea3:0xd5b765,roughness:.8}));base.position.set(center.x,floorY(floor.level),center.z);base.receiveShadow=true;group.add(base);
  const plan=new THREE.Mesh(new THREE.PlaneGeometry(PLAN_WIDTH,PLAN_DEPTH),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide,transparent:true,opacity:.94}));plan.rotation.x=-Math.PI/2;plan.position.set(center.x,floorY(floor.level)+.07,center.z);group.add(plan);
  const geometry=new THREE.SphereGeometry(.055,6,5),material=new THREE.MeshBasicMaterial({color:floor.building==="SH"?0x087f82:0xb77d18});const markers=new THREE.InstancedMesh(geometry,material,floor.rooms.length);const matrix=new THREE.Matrix4();floor.rooms.forEach((room,index)=>{matrix.setPosition(worldPoint(floor,room.x,room.z,.13));markers.setMatrixAt(index,matrix)});group.add(markers);
  const label=htmlLabel(`${floor.buildingName} · ${floor.levelLabel}`);label.position.copy(worldPoint(floor,.5,.08,.45));group.add(label);scene.add(group);floorObjects.push({floor,group});
}
status.textContent=`Loading ${floorData.roomCount.toLocaleString()} rooms…`;
await Promise.all(floorData.floors.map(addFloor));

const facilities=new THREE.Group();scene.add(facilities);const elevatorCabins=[];
function addFacilities(building){
  const buildingFloors=floorData.floors.filter(floor=>floor.building===building).sort((a,b)=>a.level-b.level),min=floorY(buildingFloors[0].level),max=floorY(buildingFloors.at(-1).level);
  const elevator=connectorWorld[building].elevator,shaft=new THREE.Mesh(new THREE.BoxGeometry(.72,max-min+.8,.72),new THREE.MeshStandardMaterial({color:0x5b8d98,transparent:true,opacity:.25,metalness:.3}));shaft.position.set(elevator.x,(min+max)/2,elevator.z);facilities.add(shaft);const cabin=new THREE.Mesh(new THREE.BoxGeometry(.56,.5,.56),new THREE.MeshStandardMaterial({color:0x087f82,metalness:.5}));cabin.position.set(elevator.x,min+.3,elevator.z);cabin.userData={min,max};facilities.add(cabin);elevatorCabins.push(cabin);
  const stair=connectorWorld[building].stairs;for(let index=0;index<buildingFloors.length-1;index++){const low=buildingFloors[index],high=buildingFloors[index+1];for(let step=0;step<9;step++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.6,.09,.18),new THREE.MeshStandardMaterial({color:0x526970}));mesh.position.set(stair.x,floorY(low.level)+.12+(floorY(high.level)-floorY(low.level))*step/9,stair.z-.45+step*.1);facilities.add(mesh)}}
  const escalator=connectorWorld[building].escalator;for(let index=0;index<buildingFloors.length-1;index++){const low=buildingFloors[index],high=buildingFloors[index+1];for(let step=0;step<10;step++){const mesh=new THREE.Mesh(new THREE.BoxGeometry(.56,.06,.15),new THREE.MeshStandardMaterial({color:step%2?0xd1aa4b:0xefcf78,metalness:.25}));mesh.position.set(escalator.x,floorY(low.level)+.12+(floorY(high.level)-floorY(low.level))*step/10,escalator.z-.42+step*.09);mesh.userData.escalator=true;facilities.add(mesh)}}
  for(const [name,point,color] of [["ELEVATOR",elevator,"#087f82"],["STAIRS",stair,"#455b61"],["ESCALATOR",escalator,"#9a7223"]]){const label=htmlLabel(name,color);label.position.set(point.x,floorY(4)+.65,point.z);facilities.add(label)}
}
addFacilities("SH");addFacilities("WEH");
const sh4=floorById.get("SH-4"),weh4=floorById.get("WEH-4"),bridgeStart=worldPoint(sh4,bridgePortal.SH.x,bridgePortal.SH.z,.14),bridgeEnd=worldPoint(weh4,bridgePortal.WEH.x,bridgePortal.WEH.z,.14);const bridgeLength=bridgeStart.distanceTo(bridgeEnd),bridge=new THREE.Mesh(new THREE.BoxGeometry(bridgeLength,.16,.72),new THREE.MeshStandardMaterial({color:0xdde4e2,metalness:.2}));bridge.position.copy(bridgeStart).lerp(bridgeEnd,.5);bridge.position.y=floorY(4)+.1;bridge.rotation.y=-Math.atan2(bridgeEnd.z-bridgeStart.z,bridgeEnd.x-bridgeStart.x);scene.add(bridge);

class Heap{constructor(){this.a=[]}push(value,priority){const a=this.a,node=[priority,value];a.push(node);let i=a.length-1;while(i){const p=(i-1)>>1;if(a[p][0]<=priority)break;a[i]=a[p];i=p}a[i]=node}pop(){const a=this.a,root=a[0],last=a.pop();if(a.length){let i=0;while(true){let c=i*2+1;if(c>=a.length)break;if(c+1<a.length&&a[c+1][0]<a[c][0])c++;if(a[c][0]>=last[0])break;a[i]=a[c];i=c}a[i]=last}return root?.[1]}get length(){return this.a.length}}
function dilate(source,width,height,radius){const horizontal=new Uint8Array(source.length),out=new Uint8Array(source.length);for(let y=0;y<height;y++){let count=0;for(let x=0;x<width;x++){if(x+radius<width)count+=source[y*width+x+radius];if(x-radius-1>=0)count-=source[y*width+x-radius-1];horizontal[y*width+x]=count>0?1:0}}for(let x=0;x<width;x++){let count=0;for(let y=0;y<height;y++){if(y+radius<height)count+=horizontal[(y+radius)*width+x];if(y-radius-1>=0)count-=horizontal[(y-radius-1)*width+x];out[y*width+x]=count>0?1:0}}return out}
function prepareGrid(floor){
  if(floor.grid)return floor.grid;
  const width=420,height=Math.round(width*floor.imageElement.height/floor.imageElement.width),canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;
  const context=canvas.getContext("2d",{willReadFrequently:true});context.drawImage(floor.imageElement,0,0,width,height);
  const rgba=context.getImageData(0,0,width,height).data,dark=new Uint8Array(width*height);
  for(let i=0;i<dark.length;i++){const p=i*4,l=.2126*rgba[p]+.7152*rgba[p+1]+.0722*rgba[p+2];dark[i]=l<165?1:0}
  const closed=dilate(dark,width,height,5),outside=new Uint8Array(dark.length),queue=[];
  for(let x=0;x<width;x++)queue.push(x,(height-1)*width+x);for(let y=0;y<height;y++)queue.push(y*width,y*width+width-1);
  for(let head=0;head<queue.length;head++){const i=queue[head];if(outside[i]||closed[i])continue;outside[i]=1;const x=i%width,y=Math.floor(i/width);if(x)queue.push(i-1);if(x+1<width)queue.push(i+1);if(y)queue.push(i-width);if(y+1<height)queue.push(i+width)}
  const xs=floor.rooms.map(room=>room.x),zs=floor.rooms.map(room=>room.z),margin=.035,bounds={left:Math.max(0,Math.min(...xs)-margin),right:Math.min(1,Math.max(...xs)+margin),top:Math.max(0,Math.min(...zs)-margin),bottom:Math.min(1,Math.max(...zs)+margin)},allowed=new Uint8Array(dark.length);
  for(let i=0;i<allowed.length;i++){const x=(i%width)/(width-1),z=Math.floor(i/width)/(height-1),within=x>=bounds.left&&x<=bounds.right&&z>=bounds.top&&z<=bounds.bottom;allowed[i]=!dark[i]&&within&&(!outside[i]||closed[i])?1:0}
  floor.grid={width,height,allowed,dark,closed,outside};return floor.grid;
}
function nearestAllowed(grid,point){const ox=Math.round(point.x*(grid.width-1)),oy=Math.round(point.z*(grid.height-1));for(let radius=0;radius<28;radius++)for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){if(Math.abs(dx)!==radius&&Math.abs(dy)!==radius)continue;const x=ox+dx,y=oy+dy;if(x>=0&&y>=0&&x<grid.width&&y<grid.height&&grid.allowed[y*grid.width+x])return {x,y}}return null}
function rasterPath(floor,start,end){const cacheKey=`${floor.id}:${start.x.toFixed(4)},${start.z.toFixed(4)}:${end.x.toFixed(4)},${end.z.toFixed(4)}`;if(floorPathCache.has(cacheKey))return floorPathCache.get(cacheKey);const grid=prepareGrid(floor),a=nearestAllowed(grid,start),b=nearestAllowed(grid,end);if(!a)throw new Error(`No mapped walkspace near start point ${start.x.toFixed(3)}, ${start.z.toFixed(3)} on ${floor.buildingName} ${floor.levelLabel}`);if(!b)throw new Error(`No mapped walkspace near destination point ${end.x.toFixed(3)}, ${end.z.toFixed(3)} on ${floor.buildingName} ${floor.levelLabel}`);const size=grid.width*grid.height,g=new Float32Array(size);g.fill(Infinity);const previous=new Int32Array(size);previous.fill(-1);const startIndex=a.y*grid.width+a.x,target=b.y*grid.width+b.x,heap=new Heap();g[startIndex]=0;heap.push(startIndex,0);const moves=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];while(heap.length){const current=heap.pop();if(current===target)break;const x=current%grid.width,y=Math.floor(current/grid.width);for(const [dx,dy] of moves){const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=grid.width||yy>=grid.height)continue;const next=yy*grid.width+xx;if(!grid.allowed[next])continue;if(dx&&dy&&(!grid.allowed[y*grid.width+xx]||!grid.allowed[yy*grid.width+x]))continue;const candidate=g[current]+(dx&&dy?Math.SQRT2:1);if(candidate<g[next]){g[next]=candidate;previous[next]=current;heap.push(next,candidate+Math.hypot(xx-b.x,yy-b.y))}}}if(previous[target]<0&&target!==startIndex)throw new Error(`No human-reachable walkspace route on ${floor.buildingName} ${floor.levelLabel}`);const pixels=[];for(let current=target;current!==-1;current=previous[current]){pixels.push(current);if(current===startIndex)break}pixels.reverse();const simplified=[pixels[0]];let priorDirection;for(let index=1;index<pixels.length;index++){const dx=pixels[index]%grid.width-pixels[index-1]%grid.width,dy=Math.floor(pixels[index]/grid.width)-Math.floor(pixels[index-1]/grid.width),direction=`${dx},${dy}`;if(priorDirection&&direction!==priorDirection)simplified.push(pixels[index-1]);priorDirection=direction}simplified.push(pixels.at(-1));const path=simplified.map(index=>({x:(index%grid.width)/(grid.width-1),z:Math.floor(index/grid.width)/(grid.height-1)}));floorPathCache.set(cacheKey,path);floorPathCache.set(`${floor.id}:${end.x.toFixed(4)},${end.z.toFixed(4)}:${start.x.toFixed(4)},${start.z.toFixed(4)}`,[...path].reverse());return path}

function appendFloorPath(route,floor,start,end){const normalized=rasterPath(floor,start,end);for(const point of normalized)route.points.push(worldPoint(floor,point.x,point.z,.2));route.steps.push(`Follow mapped walkspace on ${floor.buildingName} ${floor.levelLabel}.`)}
function appendVertical(route,building,fromFloor,toFloor,mode){const connector=connectorWorld[building][mode],levels=floorData.floors.filter(f=>f.building===building&&f.level>=Math.min(fromFloor.level,toFloor.level)&&f.level<=Math.max(fromFloor.level,toFloor.level)).sort((a,b)=>fromFloor.level<toFloor.level?a.level-b.level:b.level-a.level);for(const floor of levels){const p=connector.clone();p.y=floorY(floor.level)+.2;if(mode==="stairs"){p.x+=levels.indexOf(floor)%2?.18:-.18;p.z+=levels.indexOf(floor)%2?.16:-.16}route.points.push(p)}route.types.push(mode);route.steps.push(`${mode==="elevator"?"Take the elevator":"Use the stairs"} to ${toFloor.buildingName} ${toFloor.levelLabel}.`)}
function connectorNorm(floor,mode){return normalizedPoint(floor,connectorWorld[floor.building][mode])}
function roomNorm(room){return {x:room.x,z:room.z}}
async function planRoute(startRoom,endRoom,accessible){const route={points:[],steps:[`Exit ${startRoom.name} through its mapped doorway.`],types:[]},startFloor=floorById.get(startRoom.floorId),endFloor=floorById.get(endRoom.floorId),mode=accessible?"elevator":"stairs";
  if(startFloor.id===endFloor.id)appendFloorPath(route,startFloor,roomNorm(startRoom),roomNorm(endRoom));
  else if(startFloor.building===endFloor.building){appendFloorPath(route,startFloor,roomNorm(startRoom),connectorNorm(startFloor,mode));appendVertical(route,startFloor.building,startFloor,endFloor,mode);appendFloorPath(route,endFloor,connectorNorm(endFloor,mode),roomNorm(endRoom));}
  else{const startBridge=floorById.get(`${startFloor.building}-4`),endBridge=floorById.get(`${endFloor.building}-4`);let startAt=roomNorm(startRoom);if(startFloor.level!==4){appendFloorPath(route,startFloor,startAt,connectorNorm(startFloor,mode));appendVertical(route,startFloor.building,startFloor,startBridge,mode);startAt=connectorNorm(startBridge,mode)}appendFloorPath(route,startBridge,startAt,bridgePortal[startFloor.building]);route.points.push(startFloor.building==="SH"?bridgeStart:bridgeEnd,startFloor.building==="SH"?bridgeEnd:bridgeStart);route.types.push("bridge");route.steps.push("Cross between buildings through the Level 4 bridge.");let endAt=bridgePortal[endFloor.building];if(endFloor.level!==4){appendFloorPath(route,endBridge,endAt,connectorNorm(endBridge,mode));appendVertical(route,endFloor.building,endBridge,endFloor,mode);endAt=connectorNorm(endFloor,mode)}appendFloorPath(route,endFloor,endAt,roomNorm(endRoom));}
  route.steps.push(`Enter ${endRoom.name}.`);return route}

let routeGroup,routeLine,autoRotate=false;
function pin(position,color){const group=new THREE.Group(),cone=new THREE.Mesh(new THREE.ConeGeometry(.18,.5,16),new THREE.MeshStandardMaterial({color})),ring=new THREE.Mesh(new THREE.TorusGeometry(.22,.045,8,20),new THREE.MeshBasicMaterial({color}));cone.rotation.x=Math.PI;cone.position.y=.29;ring.rotation.x=Math.PI/2;group.add(cone,ring);group.position.copy(position);return group}
function drawRoute(route,start,end){if(routeGroup){routeGroup.traverse(object=>{if(object.isCSS2DObject)object.element.remove();object.geometry?.dispose();if(object.material)Object.values(Array.isArray(object.material)?object.material:[object.material]).forEach(material=>material.dispose())});scene.remove(routeGroup)}routeGroup=new THREE.Group();const geometry=new THREE.BufferGeometry().setFromPoints(route.points),material=new THREE.LineDashedMaterial({color:0xe65f48,dashSize:.2,gapSize:.1});routeLine=new THREE.Line(geometry,material);routeLine.computeLineDistances();routeGroup.add(routeLine,pin(route.points[0],0xe65f48),pin(route.points.at(-1),0x087f82));const startLabel=htmlLabel(start.name,"#e65f48");startLabel.position.copy(route.points[0]).add(new THREE.Vector3(0,.7,0));const endLabel=htmlLabel(end.name,"#087f82");endLabel.position.copy(route.points.at(-1)).add(new THREE.Vector3(0,.7,0));routeGroup.add(startLabel,endLabel);scene.add(routeGroup);const middle=route.points[Math.floor(route.points.length/2)];controls.target.copy(middle);camera.position.set(middle.x+11,middle.y+10,middle.z+13);controls.update()}

const from=document.querySelector("#from"),to=document.querySelector("#to"),result=document.querySelector("#result"),accessible=document.querySelector("#accessible"),options=document.querySelector("#room-options"),floorFilter=document.querySelector("#floor-filter");
for(const floor of [...floorData.floors].sort((a,b)=>a.building.localeCompare(b.building)||a.level-b.level)){const option=document.createElement("option");option.value=floor.id;option.textContent=`${floor.buildingName} ${floor.levelLabel}`;floorFilter.append(option);for(const room of floor.rooms){const item=document.createElement("option");item.value=room.name;item.label=`${floor.buildingName} · ${floor.levelLabel}`;options.append(item)}}
from.value="Scott 4N103";to.value="Wean 4325";
function selectedRoom(input){return roomByName.get(input.value.trim().toLowerCase())}
async function show(){const start=selectedRoom(from),end=selectedRoom(to);if(!start||!end){result.className="directions show";result.innerHTML="<div class='route-head'><h2>Select a room from the list</h2></div>";return}if(start.id===end.id){result.className="directions show";result.innerHTML="<div class='route-head'><h2>You are already there</h2></div>";return}document.querySelector("#go").disabled=true;status.textContent="Checking mapped walkspace…";try{const route=await planRoute(start,end,accessible.checked),mode=route.types.includes("elevator")?"Elevator":route.types.includes("stairs")?"Stairs":route.types.includes("bridge")?"Level 4 bridge":"Direct walkspace";drawRoute(route,start,end);result.className="directions show";result.innerHTML=`<div class="route-head"><h2>${start.name} → ${end.name}</h2><span>${route.steps.length} steps</span></div><div class="route-meta"><span class="recommended">RECOMMENDED</span><span>${mode}</span><span>Map walkspace</span>${route.types.includes("bridge")?"<span>Bridge required</span>":""}</div><ol>${route.steps.map((step,index)=>`<li><b>${index+1}</b><span>${step}</span></li>`).join("")}</ol>`;status.textContent=`Reachable route · ${start.name} → ${end.name}`}catch(error){result.className="directions show";result.innerHTML=`<div class="route-head"><h2>No verified route</h2></div><p>${error.message}. The app will not draw a path through walls or air.</p>`;status.textContent="No verified walkspace route"}finally{document.querySelector("#go").disabled=false}}
function applyVisibility(){const building=document.querySelector("[data-building].active").dataset.building,floorId=floorFilter.value;for(const item of floorObjects)item.group.visible=(building==="all"||item.floor.building===building)&&(floorId==="all"||item.floor.id===floorId)}
document.querySelectorAll("[data-building]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-building]").forEach(item=>item.classList.remove("active"));button.classList.add("active");floorFilter.value="all";applyVisibility()});floorFilter.onchange=applyVisibility;
document.querySelector("#go").onclick=show;document.querySelector("#swap").onclick=()=>{const value=from.value;from.value=to.value;to.value=value;show()};document.querySelector("#reset-view").onclick=()=>{camera.position.set(28,20,28);controls.target.set(0,floorY(4),0);controls.update()};document.querySelector("#rotate").onclick=event=>{autoRotate=!autoRotate;event.currentTarget.classList.toggle("active",autoRotate)};document.querySelectorAll(".examples button").forEach(button=>button.onclick=()=>{from.value=rooms.get(button.dataset.from)?.name||"";to.value=rooms.get(button.dataset.to)?.name||"";show()});
function resize(){const width=container.clientWidth,height=container.clientHeight;camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false);labelRenderer.setSize(width,height)}function animate(time=0){requestAnimationFrame(animate);if(autoRotate)scene.rotation.y+=.002;if(routeLine)routeLine.material.dashOffset-=.01;for(const cabin of elevatorCabins)cabin.position.y=cabin.userData.min+.3+(Math.sin(time*.0007)+1)*(cabin.userData.max-cabin.userData.min)/2;for(const object of facilities.children)if(object.userData.escalator)object.material.emissive.setScalar(.05+.05*Math.sin(time*.004+object.position.y));controls.update();renderer.render(scene,camera);labelRenderer.render(scene,camera)}
camera.position.set(28,20,28);controls.target.set(0,floorY(4),0);resize();animate();addEventListener("resize",resize);status.textContent=`${floorData.roomCount.toLocaleString()} mapped spaces · drag to rotate`;
